# Generated by Django 3.2.5 on 2021-07-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210726_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Task',
        ),
    ]
